version: "3"

services:
  postgres_n8n:
    image: postgres:latest
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n_password
    volumes:
      - postgres_n8n_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U n8n -d n8n" ]
      interval: 10s
      retries: 5
  postgres_docassemble:
    image: postgres:latest
    environment:
      - POSTGRES_DB=docassemble
      - POSTGRES_USER=docassemble
      - POSTGRES_PASSWORD=docassemble_password
    volumes:
      - postgres_docassemble_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U docassemble -d docassemble" ]
      interval: 10s
      retries: 5
  postgres_orbeon:
    image: postgres:latest
    environment:
      - POSTGRES_DB=orbeon
      - POSTGRES_USER=orbeon
      - POSTGRES_PASSWORD=orbeon_password
    volumes:
      - postgres_orbeon_data:/var/lib/postgresql/data
      - ./orbeon/ddl.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5431:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U orbeon_user -d orbeon" ]
      interval: 10s
      retries: 5

  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres_n8n
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n_password
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password
    volumes:
      - n8n_data:/root/.n8n
    depends_on:
      postgres_n8n:
        condition: service_healthy
  docassemble:
    image: jhpyle/docassemble
    ports:
      - "80:80"
    environment:
      - DB_TYPE=postgresql
      - POSTGRES_DB=docassemble
      - POSTGRES_USER=docassemble
      - POSTGRES_PASSWORD=docassemble_password
      - POSTGRES_HOST=postgres_docassemble
    volumes:
      - docassemble_data:/usr/share/docassemble/files
    depends_on:
      postgres_docassemble:
        condition: service_healthy
  orbeon:
    build:
      context: ./orbeon
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./orbeon/properties-local.xml:/usr/local/tomcat/webapps/orbeon/WEB-INF/resources/config/properties-local.xml
      - ./orbeon/web.xml:/usr/local/tomcat/webapps/orbeon/WEB-INF/web.xml
      - ./orbeon/server.xml:/usr/local/tomcat/conf/server.xml
      - ./orbeon/context.xml:/usr/local/tomcat/webapps/orbeon/META-INF/context.xml
    depends_on:
      postgres_orbeon:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres_n8n
      - postgres_docassemble
      - postgres_orbeon
    volumes:
      - pgadmin_data:/var/lib/pgadmin


volumes:
  postgres_n8n_data:
  postgres_docassemble_data:
  postgres_orbeon_data:
  docassemble_data:
  n8n_data:
  pgadmin_data:
